# Generated by Django 2.0.3 on 2018-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=500)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('lastEditTime', models.DateTimeField(auto_now=True)),
                ('owner', models.IntegerField()),
                ('label', models.IntegerField(null=True)),
                ('cover', models.CharField(max_length=30)),
            ],
        ),
    ]
