# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180317_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='book_img'),
        ),
        migrations.AlterField(
            model_name='book',
            name='introduction',
            field=models.TextField(max_length=500),
        ),
    ]
