# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180413_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=999, null=True, verbose_name='价格'),
        ),
    ]
