# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180331_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'get_latest_by': 'lastEditTime', 'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'createTime', 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'get_latest_by': 'labelNum', 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=30, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=20, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='book_img', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='book',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='introduction',
            field=models.TextField(max_length=500, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='book',
            name='label',
            field=models.IntegerField(null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lastEditTime',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='所在书目'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='label',
            name='labelName',
            field=models.CharField(max_length=10, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='label',
            name='labelNum',
            field=models.IntegerField(verbose_name='编号'),
        ),
    ]
