# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180331_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='无', max_length=30),
        ),
    ]
