# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0010_auto_20180405_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authorInfo',
            field=models.CharField(default='', max_length=500, verbose_name='作者信息'),
        ),
        migrations.AddField(
            model_name='book',
            name='originName',
            field=models.CharField(default='', max_length=30, verbose_name='原作名'),
        ),
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(default=0, verbose_name='页数'),
        ),
        migrations.AddField(
            model_name='book',
            name='press',
            field=models.DateTimeField(null=True, verbose_name='出版时间'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=99999, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=0, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=30, verbose_name='书名'),
        ),
        migrations.AddField(
            model_name='praise',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Comment', verbose_name='被赞评论'),
        ),
        migrations.AddField(
            model_name='praise',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞者'),
        ),
    ]
