# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='praise',
            field=models.IntegerField(default=0, verbose_name='赞数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authorInfo',
            field=models.TextField(default='', max_length=500, verbose_name='作者信息'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praiseToComment', to='book.Comment', verbose_name='被赞评论'),
        ),
    ]
