# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20180406_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pressTime',
            field=models.DateTimeField(null=True, verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='press',
            field=models.CharField(max_length=30, null=True, verbose_name='出版社'),
        ),
    ]
