# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20180406_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelName', models.CharField(max_length=10, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '父标签',
                'verbose_name_plural': '父标签',
            },
        ),
        migrations.CreateModel(
            name='SLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelName', models.CharField(max_length=10, verbose_name='标签名')),
                ('fatherLabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.FLabel', verbose_name='父标签')),
            ],
            options={
                'verbose_name': '子标签',
                'verbose_name_plural': '子标签',
            },
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AlterField(
            model_name='book',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.SLabel', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
    ]
