# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20180408_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorPhoto',
            field=models.ImageField(null=True, upload_to='book_img', verbose_name='作者照片'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(max_length=30, null=True, verbose_name='译者'),
        ),
    ]
