# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20180408_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.FloatField(null=True, verbose_name='评分'),
        ),
    ]
