# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_book_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.FloatField(default=5, null=True, verbose_name='评分'),
        ),
    ]
