# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='用户', max_length=20),
        ),
    ]
