# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isDisplay',
            field=models.BooleanField(default=False, verbose_name='文章展示'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_cate',
            field=models.CharField(choices=[('小说', '小说'), ('散文', '散文'), ('感悟', '感悟'), ('新闻', '新闻')], default='小说', max_length=5, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='article',
            name='isHomeArticle',
            field=models.BooleanField(default=False, verbose_name='首页文章'),
        ),
    ]
