# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180410_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homearticle',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '用户文章', 'verbose_name_plural': '用户文章'},
        ),
        migrations.AddField(
            model_name='article',
            name='sort',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.DeleteModel(
            name='HomeArticle',
        ),
    ]
