# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_article',
            name='content',
            field=models.CharField(max_length=145, verbose_name='内容'),
        ),
    ]
