# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180410_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sort',
        ),
        migrations.AddField(
            model_name='article',
            name='isHomeArticle',
            field=models.BooleanField(default=False),
        ),
    ]
