# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(storage=main.storage.ImageStorage(), upload_to='images'),
        ),
    ]
